### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by MarkusEicher**
Hello Anusha

First let me thank you for giving me the opportunity to contribute to your interesting project. I was looking for another one to complete Hacktoberfest as a contributor. Currently I'm learning HTML, CSS, JavaScript and a bit React.js. The design of a landing page for a photographer seemed a good training project for all of these skills. I proposed a collage to be used as the design, mainly because I think it is easy to setup as a mobile first and responsive page. I used Framer as the design tool, and I imported one of the free templates into my workspace. A clickable prototype is linked in the README.md file.

I ask you to review my PR and merge it into your main branch if it matches your requirements. If not, please let me know what you would like me to change or add. Thanks for your efforts and I'm looking forward to your answer.

Best regards
Markus Eicher

### CODE REVIEW

**Review by anushas-dev — APPROVED** [review]
Thank you @MarkusEicher. Appreciate the way you reasoned the design with respect to different screen sizes and also shared an example of code snippets can be generated via Framer App.

**Comment by anushas-dev** [comment]
This PR covers for Issue #1

**Comment by MarkusEicher** [comment]
Thanks. I didn't include the closes #1 term in the PR because I was not sure if you wanted it to be closed or if you need more examples from others for collage sites. Was a pleasure to contribute. Please let me know, if I can do something for this project. I'm pretty busy, but I will try to help out. See you later.

**Comment by anushas-dev** [comment]
Thank you, Markus. Will definitely look for more contributions and open more threads for ideas which anyone can pick up based on their interest. This project was primarily to encourage more participation for hacktoberfest and to give myself an exposure of being a maintainer.

**Pull request merged**
